=== Airex/ACT.SpecialSpellTimer/ACT.SpecialSpellTimer.Core/resources/timeline/Timeline.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  targetNamespace="https://github.com/anoyetta/Hojoring/Timeline"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--
  Timeline 定義ファイル XML Scheme
  (c) anoyetta, 2018
  -->

  <!-- Activity -->
  <xs:complexType name="Activity">
    <xs:attribute name="time" type="xs:duration" use="required" />
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="text" type="xs:string" use="optional" />
    <xs:attribute name="sync" type="xs:string" use="optional" />
    <xs:attribute name="sync-s" type="xs:double" use="optional" default="-12" />
    <xs:attribute name="sync-e" type="xs:double" use="optional" default="12" />
    <xs:attribute name="goto" type="xs:string" use="optional" />
    <xs:attribute name="call" type="xs:string" use="optional" />
    <xs:attribute name="notice" type="xs:string" use="optional" />
    <xs:attribute name="notice-d" use="optional" default="Both">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Both" />
          <xs:enumeration value="Main" />
          <xs:enumeration value="Sub" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="notice-o" type="xs:double" use="optional" default="-6" />
    <xs:attribute name="style" type="xs:string" use="optional" />
    <xs:attribute name="enabled" type="xs:boolean" use="optional" default="true" />
  </xs:complexType>

  <!-- Trigger -->
  <xs:complexType name="Trigger">
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="sync" type="xs:string" use="optional" />
    <xs:attribute name="goto" type="xs:string" use="optional" />
    <xs:attribute name="call" type="xs:string" use="optional" />
    <xs:attribute name="notice" type="xs:string" use="optional" />
    <xs:attribute name="notice-d" use="optional" default="Both">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Both" />
          <xs:enumeration value="Main" />
          <xs:enumeration value="Sub" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="enabled" type="xs:boolean" use="optional" default="true" />
  </xs:complexType>

  <!-- Sub -->
  <xs:complexType name="Sub">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="a" type="Activity" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" use="optional" />
    <xs:attribute name="enabled" type="xs:boolean" use="optional" default="true" />
  </xs:complexType>

  <!-- Default -->
  <xs:complexType name="Default">
    <xs:attribute name="target-element" type="xs:string" use="required" />
    <xs:attribute name="target-attr" type="xs:string" use="required" />
    <xs:attribute name="value" type="xs:string" use="required" />
    <xs:attribute name="enabled" type="xs:boolean" use="optional" default="true" />
  </xs:complexType>

  <!-- Timeline -->
  <xs:complexType name="Timeline">
    <xs:choice>
      <xs:element name="name" type="xs:string" nillable="false" minOccurs="1" maxOccurs="1" />
      <xs:element name="zone" type="xs:string" nillable="false" minOccurs="1" maxOccurs="1" />
      <xs:element name="locale" default="JA" nillable="false" minOccurs="1" maxOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="EN" />
            <xs:enumeration value="JA" />
            <xs:enumeration value="FR" />
            <xs:enumeration value="DE" />
            <xs:enumeration value="KO" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="a" type="Activity" minOccurs="1" maxOccurs="unbounded" />
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="t" type="Trigger" />
        <xs:element name="s" type="Sub" />
        <xs:element name="default" type="Default" />
      </xs:choice>
    </xs:choice>
  </xs:complexType>

  <!-- timeline element -->
  <xs:element name="timeline" type="Timeline" />
</xs:schema>

=== Airex/ACT.SpecialSpellTimer/ACT.SpecialSpellTimer.Core/resources/timeline/ExampleTimeline3.Jump.xml
<?xml version="1.0" encoding="utf-8"?>
<timeline
  xmlns="https://github.com/anoyetta/Hojoring/Timeline"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://github.com/anoyetta/Hojoring/Timeline https://raw.githubusercontent.com/anoyetta/ACT.SpecialSpellTimer/master/ACT.SpecialSpellTimer.Core/resources/timeline/Timeline.xsd">

  <name>極白虎征魂戦(J)</name>
  <zone>The Jade Stoa (Dummy)</zone>
  <locale>JA</locale>

  <!--
  ジャンプステートメントのテスト用
  goto, call 及び t の動作確認用です。
  実用向けではありません。
  -->

  <!--
  <a time="00:00" sync="オオオオオ……この衝動、もはや止められん！" call="フェーズ1" />
  <a time="01:26" sync="駆けろ、我が半身ッ！ 歯向かう者どもに、牙と爪を突き立ててやれ！" call="フェーズ2" />
  <a time="04:28" sync="ほう……凌いで見せたか…… ならば、全力を以て応えよう！" goto="最終フェーズ" />
  -->
  <t sync="オオオオオ……この衝動、もはや止められん！" call="フェーズ1" />
  <t sync="駆けろ、我が半身ッ！ 歯向かう者どもに、牙と爪を突き立ててやれ！" call="フェーズ2" />
  <t sync="ほう……凌いで見せたか…… ならば、全力を以て応えよう！" goto="最終フェーズ" />

  <s name="フェーズ1">
    <a time="00:06" text="風雷波動" notice="次は、風雷波動。" />
    <a time="00:12" text="天雷掌" notice="次は、天雷掌。" />
    <a time="00:22" text="呪縛雷" notice="次は、呪縛雷。" />
    <a time="00:27" sync="捉えたぞ！　叩きのめしてくれるわ！" />
    <a enabled="False" time="00:29" text="Marker:003E" sync="1B:(?&lt;pcid&gt;.{8}):&lt;PC&gt;:0000:0000:003E:0000:0000:0000:" />
    <a time="00:29" text="乾坤一擲" notice="次は、乾坤一擲。" />
    <a time="00:37" text="呪縛雷" notice="次は、呪縛雷。" />
    <a time="00:37" sync="まだだッ！　これで終いと思うなよ！" />
    <a enabled="False" time="00:39" text="Marker:003E" sync="1B:(?&lt;pcid&gt;.{8}):&lt;PC&gt;:0000:0000:003E:0000:0000:0000:" />
    <a time="00:39" text="乾坤一擲" notice="次は、乾坤一擲。" />
    <a time="00:54" sync="吹けよ、荒れよ、我がアラミタマ！" />
    <a time="00:55" text="無間地獄" notice="次は、無間地獄。" />
    <a time="01:00" text="風雷波動" notice="次は、風雷波動。" />
    <a time="01:07" text="祟り風" notice="次は、祟り風。" />
    <a time="01:12" text="雷火一閃" notice="次は、雷火一閃。" />
  </s>

  <s name="フェーズ2">
    <a time="00:02" text="半獣舞踏" notice="次は、半獣舞踏。" />
    <a time="00:12" text="風雷波動" notice="次は、風雷波動。" />
    <a time="00:17" text="鉄爪斬" notice="次は、鉄爪斬。" />
    <a time="00:22" text="天雷掌" notice="次は、天雷掌。" />
    <a time="00:23" text="鉄爪斬" notice="次は、鉄爪斬。" />
    <a time="00:33" text="遠雷" notice="次は、遠雷。" />
    <a time="00:36" text="白帝衝" notice="次は、白帝衝。" />
    <a time="00:37" text="雷火一閃" notice="次は、雷火一閃。" />
    <a time="00:41" text="風雷波動" notice="次は、風雷波動。" />
    <a time="00:49" text="雷声" notice="次は、雷声。" />
    <a time="00:51" text="雷轟" notice="次は、雷轟。" />
    <a time="00:52" text="Add 荒魂" notice="次は、荒魂。" />
    <a time="01:12" text="雷轟" notice="次は、雷轟。" />
  </s>

  <a name="最終フェーズ" time="04:38" text="天雷掌" notice="次は、天雷掌。" />
  <a time="04:48" sync="天つ雷よ、焼き払え！" />
  <a time="04:49" text="天つ雷" notice="次は、天つ雷。" />
  <a time="04:50" text="呪縛雷" notice="次は、呪縛雷。" />
  <a time="04:55" sync="捉えたぞ！　叩きのめしてくれるわ！" />
  <a enabled="False" time="04:57" text="Marker:003E" sync="1B:(?&lt;pcid&gt;.{8}):&lt;PC&gt;:0000:0000:003E:0000:0000:0000:" />
  <a time="04:57" text="乾坤一擲" notice="次は、乾坤一擲。" />
  <a time="05:05" text="呪縛雷" notice="次は、呪縛雷。" />
  <a time="05:06" sync="まだだッ！　これで終いと思うなよ！" />
  <a enabled="False" time="05:07" text="Marker:003E" sync="1B:(?&lt;pcid&gt;.{8}):&lt;PC&gt;:0000:0000:003E:0000:0000:0000:" />
  <a time="05:07" text="乾坤一擲" notice="次は、乾坤一擲。" />
  <a time="05:14" text="旋体脚" notice="次は、旋体脚。" />
  <a time="05:28" sync="吹けよ、荒れよ、我がアラミタマ！" />
  <a time="05:30" text="無間地獄" notice="次は、無間地獄。" />
  <a time="05:35" text="風雷波動" notice="次は、風雷波動。" />
  <a time="05:43" sync="天つ風よ、吹き荒べ！" />
  <a time="05:44" text="爆弾低気圧" sync="白虎の「爆弾低気圧」" notice="次は、爆弾低気圧。" />
  <a time="05:50" text="祟り風" notice="次は、祟り風。" />
  <a time="05:54" text="雷火一閃" notice="次は、雷火一閃。" />
  <a time="06:03" text="雷火一閃" notice="次は、雷火一閃。" />
  <a time="06:12" sync="駆けろ、我が半身ッ！ 歯向かう者どもに、牙と爪を突き立ててやれ！" />
  <a time="06:14" text="半獣舞踏" notice="次は、半獣舞踏。" />
  <a time="06:29" text="遠雷" notice="次は、遠雷。" />
  <a time="06:32" text="白帝衝" notice="次は、白帝衝。" />
  <a time="06:34" text="雷火一閃" notice="次は、雷火一閃。" />
  <a time="06:37" text="遠雷" notice="次は、遠雷。" />
  <a time="06:42" text="雷火一閃" notice="次は、雷火一閃。" />
  <a time="06:50" text="天雷掌" notice="次は、天雷掌。" />
  <a time="06:54" text="鉄爪斬" notice="次は、鉄爪斬。" />
  <a time="07:02" text="雷声" notice="次は、雷声。" />
  <a time="07:04" text="雷轟" notice="次は、雷轟。" />
  <a time="07:10" text="風雷波動" notice="次は、風雷波動。" />
  <a time="07:24" sync="さあ、余興は終いぞ！" />
  <a time="07:25" text="雷轟" notice="次は、雷轟。" />
  <a time="07:33" text="雷火一閃" notice="次は、雷火一閃。" />
  <a time="07:48" text="風雷波動" notice="次は、風雷波動。" />
  <a time="08:02" sync="天つ風よ、吹き荒べ！" />
  <a time="08:03" text="爆弾低気圧" notice="次は、爆弾低気圧。" />
  <a time="08:05" text="天つ雷" notice="次は、天つ雷。" />
  <a time="08:06" sync="天つ雷よ、焼き払え！" />
  <a time="08:09" text="呪縛雷" notice="次は、呪縛雷。" />
  <a time="08:14" sync="捉えたぞ！　叩きのめしてくれるわ！" />
  <a enabled="False" time="08:15" text="Marker:003E" sync="1B:(?&lt;pcid&gt;.{8}):&lt;PC&gt;:0000:0000:003E:0000:0000:0000:" />
  <a time="08:15" text="乾坤一擲" notice="次は、乾坤一擲。" />
  <a time="08:24" text="呪縛雷" notice="次は、呪縛雷。" />
  <a time="08:24" sync="まだだッ！　これで終いと思うなよ！" />
  <a time="08:25" text="乾坤一擲" notice="次は、乾坤一擲。" />
  <a time="08:33" text="旋体脚" notice="次は、旋体脚。" />
  <a time="08:47" text="天雷掌" notice="次は、天雷掌。" />
  <a time="08:57" text="風雷波動" notice="次は、風雷波動。" />
  <a time="09:09" text="遠雷" notice="次は、遠雷。" />
  <a time="09:16" text="天雷掌" notice="次は、天雷掌。" />
  <a time="09:28" sync="吹けよ、荒れよ、我がアラミタマ！" />
  <a time="09:30" text="無間地獄" notice="次は、無間地獄。" />
  <a time="09:35" text="風雷波動" notice="次は、風雷波動。" />
  <a time="09:43" sync="天つ風よ、吹き荒べ！" />
  <a time="09:44" text="爆弾低気圧" notice="次は、爆弾低気圧。" />
  <a time="09:50" text="祟り風" notice="次は、祟り風。" />
  <a time="09:55" text="雷火一閃" notice="次は、雷火一閃。" />
  <a time="10:04" text="雷火一閃" notice="次は、雷火一閃。" />
  <a time="10:19" text="風雷波動" notice="次は、風雷波動。" />
  <a time="10:31" sync="天つ雷よ、焼き払え！" />
  <a time="10:32" text="天つ雷" notice="次は、天つ雷。" />
  <a time="10:33" text="呪縛雷" notice="次は、呪縛雷。" />
  <a time="10:38" sync="捉えたぞ！　叩きのめしてくれるわ！" />
  <a enabled="False" time="10:39" text="Marker:003E" sync="1B:(?&lt;pcid&gt;.{8}):&lt;PC&gt;:0000:0000:003E:0000:0000:0000:" />
  <a time="10:40" text="乾坤一擲" notice="次は、乾坤一擲。" />
  <a time="10:48" sync="まだだッ！　これで終いと思うなよ！" />
  <a time="10:48" text="呪縛雷" notice="次は、呪縛雷。" />
  <a enabled="False" time="10:50" text="Marker:003E" sync="1B:(?&lt;pcid&gt;.{8}):&lt;PC&gt;:0000:0000:003E:0000:0000:0000:" />
  <a time="10:49" text="乾坤一擲" notice="次は、乾坤一擲。" />
  <a time="10:57" text="旋体脚" notice="次は、旋体脚。" />
  <a time="11:12" sync="塵芥と消えるがよい！" />
  <a time="11:12" text="風雷波動" notice="次は、風雷波動。" />
</timeline>
